name: Build Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
      - cron:  '0 11 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag arch-aur:$(date +%s)
    - uses: actions/checkout@v3
    - name: build aur packages
      run: docker -v /:/aur run  arch-aur:$(date +%s)
    
